[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

solc_version = "0.8.19"
optimizer = true
optimizer_runs = 20000

[profile.default.model_checker]
contracts = { 'src/types/twap/libraries/TWAPOrderMathLib.sol' = [ 'TWAPOrderMathLib' ] }
engine = 'chc'
targets = [
    'assert', 'underflow', 'overflow', 'divByZero', 'constantCondition', 'popEmptyArray', 'outOfBounds', 'balance'
]
timeout = 100000

[profile.ci]
verbosity = 3