name: test

on: 
  workflow_dispatch:
  pull_request:
  push:
    paths-ignore:
      - "**/*.md"

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive
          persist-credentials: false

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@8b0419c685ef46cb79ec93fbdc131174afceb730 # v1.6.0
        with:
          version: v1.2.3

      - name: Run Forge build
        run: |
          forge --version
          forge build --skip test
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv --optimize --optimizer-runs 20000 --no-match-test "fork|simulate" --fuzz-seed 672679878
        id: test
