name: test

on: 
  workflow_dispatch:
  pull_request:
  push:
    paths-ignore:
      - "**/*.md"

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          submodules: recursive
          persist-credentials: false

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@82dee4ba654bd2146511f85f0d013af94670c4de # v1.4.0
        with:
          version: v1.2.3

      - name: Run Forge build
        run: |
          forge --version
          forge build --skip test
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv --optimize --optimizer-runs 20000 --no-match-test "fork|simulate" --fuzz-seed 672679878
        id: test
